# Site settings
future: true
title: Welcome to EVAN.TOWN
description: "Maps, GIS, hikes, bikes, etc."
url: "https://evan.town"
ogimage: "img/default-ogimage.png"
author:
  name: "Evan"
  email: ""
  url: ""


# Build settings
baseurl: /
blog:
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
