# Site settings
title: Evan Thornberry
description: "Evan's site for sharing thoughts on GIS in Libraries, Maps and and other stuff. ."
url: "https://ect123.github.io/"
ogimage: "img/default-ogimage.png"
author:
  name: "Evan"
  email: ""
  url: ""


# Build settings
baseurl: /
blog: /thoughts/
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
